### ISSUE TITLE
When putting in birthday information if you use a year before 1900 the site throws an error

### ISSUE THREAD

**Issue by notthespy** [sullic7/woofer#42]
the site throws a value error if you use a year before 1900, but is strangely cool with you using a date in the future for a birthday.  THe dog is still created and any attempt to view this dog throws the same error.

**Comment by mllewellyn** [comment]
This is for dog birthday. I tested a user birthday of 1850 and it worked.

**Comment by mllewellyn** [comment]
The dog saves to the database fine but doesn't render correctly.
